### ISSUE TITLE
Multi route for the callback

### ISSUE THREAD

**Issue by MeillatTristan** [calliostro/spotify-web-api-bundle#1]
Hello,

in your doc we can have only one route to redirect : /callback

If i want divers request in divers route how i can make this ?

**Comment by calliostro** [comment]
The question was asked a while ago and I'm not sure if I understand it correctly.

As far as I know, Spotify only allows you to store one redirect URL for your app.

If the issue has not yet been resolved, please create a new entry. I will close this post.
